import { Response } from 'express';
import { AuthRequest } from '../../middleware/auth';
import { prisma } from '../../config/database';
import { sendSuccess, sendError } from '../../utils/response';
import {
  callAI,
  generateFallbackAnalysis,
  ExceptionAnalysisResponse,
  AI_MODEL,
} from './ai.service';

const EXCEPTION_ANALYSIS_SYSTEM = `You are an insurance payment reconciliation assistant for InsureFlow.
Analyze the provided payment exception and return a JSON object with these exact fields:
{
  "summary": "One-sentence summary",
  "likelyCause": "The most probable root cause",
  "financialImpact": "Financial impact statement",
  "evidence": ["Evidence point 1", "Evidence point 2"],
  "recommendedActions": ["Action 1", "Action 2", "Action 3"],
  "confidence": "HIGH|MEDIUM|LOW"
}
Rules:
- Only use data provided. Never invent facts.
- Clearly distinguish confirmed facts from possible explanations.
- Return concise, professional output suitable for a finance analyst.
- confidence must be HIGH, MEDIUM, or LOW.`;

export async function analyzeException(req: AuthRequest, res: Response): Promise<void> {
  const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;

  const exception = await prisma.paymentException.findFirst({
    where: { OR: [{ id }, { exceptionNumber: id }] },
    include: {
      policy: { include: { policyholder: true } },
      invoice: true,
      payment: true,
      notes: {
        orderBy: { createdAt: 'desc' },
        take: 3,
        include: { user: { select: { name: true } } },
      },
      mlPredictions: {
        orderBy: { createdAt: 'desc' },
        take: 4,
      },
    },
  });

  if (!exception) {
    sendError(res, 'Exception not found', 404, 'EXCEPTION_NOT_FOUND');
    return;
  }

  const exc = exception as any;

  const FALLBACK_MODELS = ['fallback-deterministic', 'fallback-on-error'];

  // Check for cached recent analysis (within 30 minutes if data unchanged)
  // Skip cache if the cached entry was generated by a fallback (not real AI)
  const recentAnalysis = await prisma.aIAnalysis.findFirst({
    where: {
      exceptionId: exc.id,
      analysisType: 'EXCEPTION_ANALYSIS',
      createdAt: { gte: new Date(Date.now() - 30 * 60 * 1000) },
      NOT: { model: { in: FALLBACK_MODELS } }, // ignore fallback-generated cache
    },
    orderBy: { createdAt: 'desc' },
  });

  if (recentAnalysis && exc.updatedAt < recentAnalysis.createdAt) {
    console.log(`[AI] Returning cached analysis (model: ${recentAnalysis.model})`);
    sendSuccess(res, {
      analysis: recentAnalysis.response,
      cached: true,
      model: recentAnalysis.model,
    });
    return;
  }

  const exceptionContext = {
    type: exc.type,
    expectedAmount: Number(exc.expectedAmount),
    actualAmount: Number(exc.actualAmount),
    difference: Number(exc.difference),
    customerName: exc.policy.policyholder.name,
    policyNumber: exc.policy.policyNumber,
    policyType: exc.policy.policyType,
    invoiceNumber: exc.invoice.invoiceNumber,
    invoiceDueDate: exc.invoice.dueDate.toISOString(),
    paymentMethod: exc.payment?.paymentMethod || 'N/A',
    transactionId: exc.payment?.transactionId || 'N/A',
    severity: exc.severity,
    status: exc.status,
    notes: exc.notes.map((n: any) => `${n.user.name}: ${n.content}`),
    mlPredictions: exc.mlPredictions.map((prediction: any) => ({
      type: prediction.predictionType,
      model: prediction.modelName,
      modelVersion: prediction.modelVersion,
      score: prediction.score,
      riskLevel: prediction.riskLevel,
      features: prediction.features,
    })),
  };

  let analysis: ExceptionAnalysisResponse;
  let model = AI_MODEL;

  try {
    const prompt = `Analyze this payment exception:\n${JSON.stringify(exceptionContext, null, 2)}`;
    const aiResponse = await callAI(EXCEPTION_ANALYSIS_SYSTEM, prompt, true);
    analysis = JSON.parse(aiResponse) as ExceptionAnalysisResponse;
  } catch (error) {
    const msg = (error as Error).message;
    if (msg === 'AI_UNAVAILABLE') {
      // No key configured — use deterministic fallback
      analysis = generateFallbackAnalysis(exceptionContext);
      model = 'fallback-deterministic';
    } else {
      // Real API error — log it, still fall back so UI works
      console.error('[AI] analyzeException failed, falling back:', msg);
      analysis = generateFallbackAnalysis(exceptionContext);
      model = 'fallback-on-error';
    }
  }

  // Save the analysis
  const saved = await prisma.aIAnalysis.create({
    data: {
      exceptionId: exc.id,
      analysisType: 'EXCEPTION_ANALYSIS',
      prompt: JSON.stringify(exceptionContext),
      response: analysis as object,
      model,
    },
  });

  // Add timeline event
  await prisma.exceptionTimelineEvent.create({
    data: {
      exceptionId: exc.id,
      userId: req.user?.id,
      eventType: 'AI_ANALYSIS',
      description: `AI exception analysis completed. Confidence: ${analysis.confidence}`,
    },
  });

  // Audit log
  await prisma.auditLog.create({
    data: {
      userId: req.user?.id,
      action: 'AI_ANALYSIS',
      entityType: 'PaymentException',
      entityId: exc.id,
      newValue: { analysisId: saved.id, model },
    },
  });

  sendSuccess(res, { analysis, cached: false, model });
}

const SUMMARY_SYSTEM = `You are an insurance reconciliation analyst. Generate a concise investigation summary.
Return plain text (not JSON). Include: case overview, key facts, investigation notes summary, and recommendation.
Keep it under 300 words. Professional tone.`;

export async function generateSummary(req: AuthRequest, res: Response): Promise<void> {
  const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;

  const exception = await prisma.paymentException.findFirst({
    where: { OR: [{ id }, { exceptionNumber: id }] },
    include: {
      policy: { include: { policyholder: true } },
      invoice: true,
      payment: true,
      notes: {
        orderBy: { createdAt: 'desc' },
        include: { user: { select: { name: true } } },
      },
      timeline: { orderBy: { createdAt: 'asc' } },
      assignedTo: { select: { name: true } },
    },
  });

  if (!exception) {
    sendError(res, 'Exception not found', 404, 'EXCEPTION_NOT_FOUND');
    return;
  }

  const exc = exception as any;

  const notesText = exc.notes.length
    ? exc.notes.map((n: any) => `- ${n.user.name}: ${n.content}`).join('\n')
    : 'No investigation notes added yet.';

  const context = `
Exception: ${exc.exceptionNumber} | Type: ${exc.type} | Severity: ${exc.severity}
Policy: ${exc.policy.policyNumber} (${exc.policy.policyType})
Customer: ${exc.policy.policyholder.name}
Invoice: ${exc.invoice.invoiceNumber} | Due: ${exc.invoice.dueDate.toISOString()}
Expected: ₹${Number(exc.expectedAmount).toLocaleString('en-IN')}
Actual: ₹${Number(exc.actualAmount).toLocaleString('en-IN')}
Difference: ₹${Number(exc.difference).toLocaleString('en-IN')}
Status: ${exc.status} | Assigned to: ${exc.assignedTo?.name || 'Unassigned'}

Investigation Notes:
${notesText}
  `.trim();

  let summary: string;

  try {
    summary = await callAI(SUMMARY_SYSTEM, context, false);
  } catch (error: any) {
    if ((error as Error).message !== 'AI_UNAVAILABLE') {
      console.error('[AI] generateSummary failed, falling back:', (error as Error).message);
    }
    // Fallback deterministic summary
    summary = `### Investigation Summary — ${exc.exceptionNumber}

**Policy:** ${exc.policy.policyNumber} (${exc.policy.policyholder.name})
**Issue:** ${exc.type.replace(/_/g, ' ')} | **Severity:** ${exc.severity}
**Expected:** ₹${Number(exc.expectedAmount).toLocaleString('en-IN')} | **Actual:** ₹${Number(exc.actualAmount).toLocaleString('en-IN')} | **Difference:** ₹${Number(exc.difference).toLocaleString('en-IN')}

**Current Status:** ${exc.status} (Assigned to: ${exc.assignedTo?.name || 'Unassigned'})

**Investigation Notes:**
${notesText}

**Recommendation:** Verify bank credit statements and confirm resolution steps before closing this exception.`;
  }

  // Save analysis
  await prisma.aIAnalysis.create({
    data: {
      exceptionId: exc.id,
      analysisType: 'INVESTIGATION_SUMMARY',
      prompt: context,
      response: { summary },
      model: AI_MODEL,
    },
  });

  sendSuccess(res, { summary });
}

const CHAT_SYSTEM = `You are the InsureFlow AI Investigation Assistant.
You help finance analysts and operations teams investigate insurance payment exceptions.
Rules:
- Only discuss the current exception context provided.
- Never invent policy information or fabricate payment details.
- If information is unavailable, clearly state that.
- Provide concise, professional answers (max 150 words).
- Do not make financial or legal decisions on behalf of the company.`;

export async function chatWithAI(req: AuthRequest, res: Response): Promise<void> {
  const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const { message } = req.body;

  if (!message?.trim()) {
    sendError(res, 'Message is required', 400, 'VALIDATION_ERROR');
    return;
  }

  const exception = await prisma.paymentException.findFirst({
    where: { OR: [{ id }, { exceptionNumber: id }] },
    include: {
      policy: { include: { policyholder: true } },
      invoice: true,
      payment: true,
    },
  });

  if (!exception) {
    sendError(res, 'Exception not found', 404, 'EXCEPTION_NOT_FOUND');
    return;
  }

  const exc = exception as any;

  // Get or create conversation
  let conversation = await prisma.aIConversation.findFirst({
    where: {
      exceptionId: exc.id,
      userId: req.user!.id,
    },
    include: {
      messages: {
        orderBy: { createdAt: 'asc' },
        take: 10, // Last 10 messages for context
      },
    },
  });

  if (!conversation) {
    conversation = await prisma.aIConversation.create({
      data: {
        exceptionId: exc.id,
        userId: req.user!.id,
      },
      include: { messages: true },
    });
  }

  // Save user message
  await prisma.aIMessage.create({
    data: {
      conversationId: conversation.id,
      role: 'USER',
      content: message.trim(),
    },
  });

  const exceptionContext = `
Current Exception Context:
- Exception: ${exc.exceptionNumber} | Type: ${exc.type.replace(/_/g, ' ')}
- Policy: ${exc.policy.policyNumber} (${exc.policy.policyType})
- Customer: ${exc.policy.policyholder.name}
- Invoice: ${exc.invoice.invoiceNumber} | Due: ${exc.invoice.dueDate.toISOString()}
- Expected: ₹${Number(exc.expectedAmount).toLocaleString('en-IN')}
- Actual: ₹${Number(exc.actualAmount).toLocaleString('en-IN')}
- Difference: ₹${Number(exc.difference).toLocaleString('en-IN')}
- Transaction: ${exc.payment?.transactionId || 'N/A'}
- Payment Method: ${exc.payment?.paymentMethod || 'N/A'}
  `.trim();

  // Build conversation history
  const history = conversation.messages.map((m: any) => ({
    role: m.role === 'USER' ? ('user' as const) : ('assistant' as const),
    content: m.content,
  }));

  let aiResponse: string;

  try {
    const aiService = await import('./ai.service');
    const aiClient = aiService.getAIClient();
    if (!aiClient) throw new Error('AI_UNAVAILABLE');

    const messages = [
      { role: 'system' as const, content: `${CHAT_SYSTEM}\n\n${exceptionContext}` },
      ...history,
      { role: 'user' as const, content: message.trim() },
    ];

    console.log(`[AI] Chat call — model: ${AI_MODEL}`);
    const response = await aiClient.chat.completions.create({
      model: AI_MODEL,
      messages,
      temperature: 0.4,
      max_tokens: 800, // Chat replies are short
    });

    aiResponse = response.choices[0]?.message?.content || 'I could not generate a response.';
  } catch (chatError: any) {
    if ((chatError as Error).message !== 'AI_UNAVAILABLE') {
      console.error('[AI] chatWithAI failed, falling back:', (chatError as Error).message);
    }
    // Deterministic fallback chat
    const q = message.toLowerCase();
    if (q.includes('why') || q.includes('flagged') || q.includes('reason')) {
      aiResponse = `This exception (${exc.exceptionNumber}) was flagged because the payment amount received did not match the expected invoice amount. The type is ${exc.type.replace(/_/g, ' ')} with a difference of ₹${Number(exc.difference).toLocaleString('en-IN')}.`;
    } else if (q.includes('investigate') || q.includes('first') || q.includes('step')) {
      aiResponse = `Start by checking the payment gateway transaction reference (${exc.payment?.transactionId || 'N/A'}) in BillingCenter logs, then verify if customer ${exc.policy.policyholder.name} made any split payments.`;
    } else if (q.includes('resolv') || q.includes('close')) {
      aiResponse = `To resolve: ensure all investigation notes are logged, verify the accounting ledger is updated, then click "Resolve Exception" to mark it as RESOLVED.`;
    } else {
      aiResponse = `Exception ${exc.exceptionNumber}: Expected ₹${Number(exc.expectedAmount).toLocaleString('en-IN')}, Received ₹${Number(exc.actualAmount).toLocaleString('en-IN')}, Difference ₹${Number(exc.difference).toLocaleString('en-IN')}. Type: ${exc.type.replace(/_/g, ' ')}. Please check gateway logs for more details.`;
    }
  }

  // Save AI response
  await prisma.aIMessage.create({
    data: {
      conversationId: conversation.id,
      role: 'ASSISTANT',
      content: aiResponse,
    },
  });

  sendSuccess(res, {
    message: aiResponse,
    conversationId: conversation.id,
  });
}

export async function getDashboardInsights(_req: AuthRequest, res: Response): Promise<void> {
  // Gather aggregate stats from database
  const [
    openExceptions,
    underpayments,
    criticals,
    failedPayments,
    invoiceAgg,
    paymentAgg,
    exceptionByType,
  ] = await Promise.all([
    prisma.paymentException.count({ where: { status: { not: 'RESOLVED' } } }),
    prisma.paymentException.aggregate({
      where: { type: 'UNDERPAYMENT', status: { not: 'RESOLVED' } },
      _count: { _all: true },
      _sum: { difference: true },
    }),
    prisma.paymentException.count({
      where: { severity: 'CRITICAL', status: { not: 'RESOLVED' } },
    }),
    prisma.payment.count({ where: { status: 'FAILED' } }),
    prisma.invoice.aggregate({
      where: { status: { not: 'CANCELLED' } },
      _sum: { totalAmount: true },
    }),
    prisma.payment.aggregate({
      where: { status: 'SUCCESS' },
      _sum: { amount: true },
    }),
    prisma.paymentException.groupBy({
      by: ['type'],
      _count: { _all: true },
    }),
  ]);

  const totalExpected = Number(invoiceAgg._sum.totalAmount || 0);
  const totalReceived = Number(paymentAgg._sum.amount || 0);
  const underpaymentTotal = Number(underpayments._sum.difference || 0);
  const reconciliationRate =
    totalExpected > 0 ? ((totalReceived / totalExpected) * 100).toFixed(1) : '0.0';

  const statsContext = {
    openExceptions,
    criticalExceptions: criticals,
    failedPayments,
    underpaymentTotal,
    underpaymentCount: underpayments._count._all,
    totalExpected,
    totalReceived,
    outstandingAmount: Math.max(0, totalExpected - totalReceived),
    reconciliationRate: parseFloat(reconciliationRate),
    exceptionsByType: exceptionByType,
  };

  const INSIGHTS_SYSTEM = `You are an insurance analytics AI. Generate strategic insights from aggregated reconciliation statistics.
Return a JSON object: { "insights": [{"title": "...", "finding": "...", "impact": "...", "recommendedAction": "...", "severity": "INFO|WARNING|HIGH"}] }
Generate 3-5 actionable insights. Be specific, reference the numbers provided.`;

  let insights: Array<{
    title: string;
    finding: string;
    impact: string;
    recommendedAction: string;
    severity: 'INFO' | 'WARNING' | 'HIGH';
  }>;

  try {
    const aiResponse = await callAI(
      INSIGHTS_SYSTEM,
      `Reconciliation Statistics:\n${JSON.stringify(statsContext, null, 2)}`,
      true
    );
    const parsed = JSON.parse(aiResponse) as { insights: typeof insights };
    insights = parsed.insights;
  } catch {
    // Fallback deterministic insights
    insights = [];

    if (underpayments._count._all > 0) {
      insights.push({
        title: 'Underpayments Dominating Outstanding Deficit',
        finding: `${underpayments._count._all} open underpayment exceptions are contributing to the outstanding deficit.`,
        impact: `₹${underpaymentTotal.toLocaleString('en-IN')} remains tied to underpayment cases.`,
        recommendedAction: 'Prioritize collection follow-up and verify whether split payments exist.',
        severity: 'HIGH',
      });
    }

    if (criticals > 0) {
      insights.push({
        title: `${criticals} Critical Exceptions Require Immediate Triage`,
        finding: `${criticals} unresolved exceptions exceed the critical severity threshold.`,
        impact: 'These cases represent a high risk of financial leakage or delayed reconciliation.',
        recommendedAction: 'Assign the cases to a senior finance analyst for immediate review.',
        severity: 'HIGH',
      });
    }

    if (failedPayments > 0) {
      insights.push({
        title: 'Payment Gateway Failures Detected',
        finding: `${failedPayments} payment attempts were recorded with a failed status.`,
        impact: 'Failed collections may increase outstanding balances and policy servicing risk.',
        recommendedAction: 'Verify gateway connectivity and customer mandate status before retrying.',
        severity: 'WARNING',
      });
    }

    insights.push({
      title: `Reconciliation Rate: ${reconciliationRate}%`,
      finding: `The current reconciliation rate is ${reconciliationRate}%.`,
      impact: 'A rate below the 95% target indicates unresolved differences in the ledger.',
      recommendedAction: 'Review the highest-value unmatched records and resolve their exceptions.',
      severity: parseFloat(reconciliationRate) >= 90 ? 'INFO' : 'WARNING',
    });
  }

  sendSuccess(res, { insights, stats: statsContext });
}

export async function naturalLanguageSearch(req: AuthRequest, res: Response): Promise<void> {
  const { query } = req.body;

  if (!query?.trim()) {
    sendError(res, 'Search query is required', 400, 'VALIDATION_ERROR');
    return;
  }

  const SEARCH_SYSTEM = `You are a search query parser for an insurance reconciliation system.
Convert the natural language query into structured filters.
Return ONLY this JSON structure:
{
  "entity": "exceptions|policies|invoices|payments",
  "filters": {
    "status": [],
    "type": [],
    "severity": [],
    "paymentMethod": [],
    "policyType": []
  },
  "search": ""
}
Valid values:
- status (exceptions): OPEN, INVESTIGATING, RESOLVED, ESCALATED
- type (exceptions): UNDERPAYMENT, OVERPAYMENT, MISSING_PAYMENT, DUPLICATE_PAYMENT, LATE_PAYMENT, PAYMENT_FAILED
- severity: LOW, MEDIUM, HIGH, CRITICAL
- Only include filter arrays that are relevant. Empty arrays = no filter.`;

  let filters: {
    entity: string;
    filters: Record<string, string[]>;
    search: string;
  };

  try {
    const aiResponse = await callAI(SEARCH_SYSTEM, query.trim(), true);
    filters = JSON.parse(aiResponse);
  } catch {
    // Fallback: basic keyword parsing
    const q = query.toLowerCase();
    filters = {
      entity: 'exceptions',
      filters: {
        status: q.includes('unresolved') || q.includes('open')
          ? ['OPEN', 'INVESTIGATING']
          : q.includes('resolved')
          ? ['RESOLVED']
          : [],
        severity: q.includes('critical')
          ? ['CRITICAL']
          : q.includes('high')
          ? ['HIGH']
          : [],
        type: q.includes('underpayment')
          ? ['UNDERPAYMENT']
          : q.includes('overpayment')
          ? ['OVERPAYMENT']
          : q.includes('missing')
          ? ['MISSING_PAYMENT']
          : [],
      },
      search: '',
    };
  }

  sendSuccess(res, { query, filters });
}
